name: melon_bouncing_example
description: "Demonstrates how to use the melon_bouncing plugin."
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter

  melon_bouncing:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/itim_regular.ttf