name: melon_bouncing
description: "Bouncing views and widgets"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.melonkemo.melon_bouncing
        pluginClass: MelonBouncingPlugin
      ios:
        pluginClass: MelonBouncingPlugin
      linux:
        pluginClass: MelonBouncingPlugin
      macos:
        pluginClass: MelonBouncingPlugin
      windows:
        pluginClass: MelonBouncingPluginCApi
      web:
        pluginClass: MelonBouncingWeb
        fileName: melon_bouncing_web.dart
